### PR TITLE
Partial fix for #79: Changes memberOf to transitiveMemberOf

### PR DESCRIPTION
**Pull request by roryclaasen**
`/transitiveMemberOf` will return all the groups from `/memberOf` as well as all the groups that a user is a nested member of

Dependency of #81, this is only fix `a`

> In my opinion #79 are two separate issues:
> a) enhancement request to replace memberOf with transitiveMemberOf
> b) fix pagination regression issue created by this [commit](https://github.com/hkamel/sonar-auth-aad/commit/d8dc93b77ccb8d41904697ba98672dda175d649a#diff-1f4964536f397e8679625954c7139bd6)

This change has been tested (with #81) on an instance of sonar qube.

Note that when signing in on my account previously only 1 api request was being sent, with this change 7 were made. Perhaps an option could exist to select either direct membership or nested membership?

### CODE REVIEW

**Comment by srvrguy** [comment]
Running some manual tests, what was taking up all the requests? Do you just have that many more groups to page through? In my small test environment, I only still have 1 request being made.

**Comment by roryclaasen** [comment]
@srvrguy Yes, it's just that I had more group pages to go through

**Comment by srvrguy** [comment]
I did some tests with the Graph API and you'd need to have a lot of groups to go to more than one page. It looks like the default limit (which we use) is 100 groups per page*, so adding a bunch of calls should only happen if you have really complex setups. I'm honestly a little curious how many people using this plugin have that many groups assigned to users.

I'm inclined to merge this as-is and consider adding an option to switch between direct assignment or nested assignment only if feedback indicates it's strongly desired.

*Note: I only tested with up to 25 groups, but comments on the documentation pages indicates that the default number returned is 100.

**Comment by roryclaasen** [comment]
@srvrguy do you know when there will be a new GitHub release of this plugin.
We can build it ourselves but prefer an official build

**Comment by srvrguy** [comment]
I'm considering posting a release candidate at some point in the next seven days, with a release in December if there are no major issues discovered.

**Pull request merged**
