### PR TITLE
update sources for SQ API V6.7 (LTS)

### PR DESCRIPTION
**Pull request by Bertk**
#22

### CODE REVIEW

**Comment by hkamel** [comment]
@srvrguy if you can review this PR ... @Bertk thanks a lot for the great efforts!

**Comment by srvrguy** [comment]
Overall, it looks good, but there are several issues that are perhaps more style related, but also make for good maintenance that I'd like to request be done before this is accepted.

First, there are a bunch of different things going on in a single commit. It's listed as just an API deprecation cleanup, but it's also making a bunch of other changes like updating WordUtils, making changes in the unit tests, reorganizing the POM, etc. The commit and message is very misleading in this way. Please break into multiple commits, each doing a single task (one commit for the API deprecation updates, one for updating dependencies like WordUtils, one for POM cleanup, one for unit test changes). They can all go in this single pull request if you want, but please keep each commit to a single conceptual change.

Second, please follow the advice over at https://chris.beams.io/posts/git-commit/ on how to make a good commit message. It's a short read, but following the general precepts of that article will make it much easier for others to follow along with what you did in a commit and help you if you need to go back.

The only other thing is that I'm not really a fan of the numbers in the subcategory titles. It's not done on any of the other settings tabs in SQ, so it stands out. It's not a blocker for this to get pulled, however if you're really attached to that.

By the way, rather than make a whole new PR, you can just modify the branch and then force-push and this PR should automatically update with the new code. You should then just comment in here to get our attention to do another review.

**Comment by srvrguy** [comment]
I'm sorry you feel this way. If you're not wanting to break apart the commits, is it okay if I take the changes and break them apart and then commit them, giving credit to you in the commit message?

**Comment by Bertk** [comment]
@srvrguy Thanks for this proposal but the answer is no. 

In my organization we use squash merge for pull requests and this PR is not used for cherry-picking for another branch. Therefor splitting up the PR into multiple commits is not necessary and it does not improve the code quality.
@hkamel 
My final statement and I will not respond anymore: The PR is OK.

**Pull request closed without merging**
